const response = {
    "routes": [
      {
        "country_crossed": false,
        "weight_name": "auto",
        "weight": 398.778,
        "duration": 292.12,
        "distance": 1526.391,
        "legs": [
          {
            "via_waypoints": [],
            "admins": [{"iso_3166_1_alpha3": "DEU", "iso_3166_1": "DE"}],
            "weight": 398.778,
            "duration": 292.12,
            "steps": [
              {
                "intersections": [
                  {
                    "classes": ["restricted"],
                    "entry": [true],
                    "bearings": [27],
                    "duration": 2.52,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.772,
                    "geometry_index": 0,
                    "location": [13.42021, 52.500157]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["tunnel", "restricted"],
                    "in": 1,
                    "bearings": [28, 207],
                    "duration": 4.32,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 6.652,
                    "geometry_index": 1,
                    "location": [13.420257, 52.500214]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["restricted"],
                    "in": 1,
                    "bearings": [28, 208],
                    "duration": 5.76,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 8.236,
                    "geometry_index": 3,
                    "location": [13.42034, 52.50031]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["tunnel", "restricted"],
                    "in": 1,
                    "bearings": [27, 208],
                    "duration": 2.52,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 4.672,
                    "geometry_index": 4,
                    "location": [13.42045, 52.500436]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["restricted"],
                    "in": 1,
                    "bearings": [29, 207],
                    "duration": 8.64,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 11.404,
                    "geometry_index": 5,
                    "location": [13.420496, 52.500492]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["tunnel", "restricted"],
                    "in": 1,
                    "bearings": [26, 209],
                    "duration": 4.68,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 7.048,
                    "geometry_index": 6,
                    "location": [13.420669, 52.500682]
                  },
                  {
                    "bearings": [21, 206],
                    "entry": [true, false],
                    "classes": ["restricted"],
                    "in": 1,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "geometry_index": 7,
                    "location": [13.420753, 52.500786]
                  }
                ],
                "maneuver": {
                  "type": "depart",
                  "instruction": "Drive northeast.",
                  "bearing_after": 27,
                  "bearing_before": 0,
                  "location": [13.42021, 52.500157]
                },
                "name": "",
                "duration": 32.04,
                "distance": 88.795,
                "driving_side": "right",
                "weight": 46.644,
                "mode": "driving",
                "geometry": "yjjccBcjbrXqB}AyAmAeBwA{F{EoB{A{JyIoEgDaDgB"
              },
              {
                "intersections": [
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [114, 201, 294],
                    "duration": 12.225,
                    "turn_weight": 19.25,
                    "turn_duration": 5.025,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 27.17,
                    "geometry_index": 8,
                    "location": [13.420805, 52.500867]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [23, 114, 294],
                    "duration": 12.807,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 14.83,
                    "geometry_index": 10,
                    "location": [13.420316, 52.501001]
                  },
                  {
                    "bearings": [114, 294],
                    "entry": [false, true],
                    "in": 0,
                    "turn_weight": 0.75,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 1,
                    "geometry_index": 13,
                    "location": [13.419455, 52.501237]
                  }
                ],
                "maneuver": {
                  "type": "end of road",
                  "instruction": "Turn left onto Oranienstraße.",
                  "modifier": "left",
                  "bearing_after": 294,
                  "bearing_before": 21,
                  "location": [13.420805, 52.500867]
                },
                "name": "Oranienstraße",
                "duration": 27.632,
                "distance": 113.044,
                "driving_side": "right",
                "weight": 45.61,
                "mode": "driving",
                "geometry": "ewkccBiocrXO|@{Fr[qJdi@iAhG[hB}AtI"
              },
              {
                "intersections": [
                  {
                    "entry": [true, false, true, true],
                    "in": 1,
                    "bearings": [23, 114, 203, 296],
                    "duration": 4.705,
                    "turn_weight": 7,
                    "turn_duration": 2.005,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 9.97,
                    "geometry_index": 14,
                    "location": [13.419284, 52.501284]
                  },
                  {
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "location": [13.419369, 52.501404],
                    "geometry_index": 16,
                    "admin_index": 0,
                    "weight": 7.482,
                    "is_urban": true,
                    "traffic_signal": true,
                    "turn_duration": 2,
                    "turn_weight": 0.75,
                    "duration": 8.12,
                    "bearings": [24, 203],
                    "out": 0,
                    "in": 1,
                    "entry": [true, false]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [23, 204, 296],
                    "duration": 0.559,
                    "turn_weight": 0.75,
                    "turn_duration": 0.019,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 1.344,
                    "geometry_index": 18,
                    "location": [13.419571, 52.501682]
                  },
                  {
                    "entry": [true, true, false],
                    "in": 2,
                    "bearings": [24, 114, 203],
                    "duration": 11.887,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 13.818,
                    "geometry_index": 19,
                    "location": [13.419589, 52.501708]
                  },
                  {
                    "entry": [true, true, false, true],
                    "in": 2,
                    "bearings": [23, 115, 204, 293],
                    "duration": 8.019,
                    "turn_weight": 1.5,
                    "turn_duration": 0.019,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 10.3,
                    "geometry_index": 21,
                    "location": [13.419982, 52.502249]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [23, 203, 293],
                    "duration": 0.807,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 1.63,
                    "geometry_index": 23,
                    "location": [13.420213, 52.502581]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [24, 203, 291],
                    "duration": 0.407,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 1.19,
                    "geometry_index": 24,
                    "location": [13.420233, 52.50261]
                  },
                  {
                    "entry": [true, true, false],
                    "in": 2,
                    "bearings": [23, 113, 204],
                    "duration": 6.819,
                    "turn_weight": 0.75,
                    "turn_duration": 0.019,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 8.23,
                    "geometry_index": 25,
                    "location": [13.420244, 52.502625]
                  },
                  {
                    "entry": [true, true, false],
                    "in": 2,
                    "bearings": [23, 114, 203],
                    "duration": 0.407,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 1.19,
                    "geometry_index": 26,
                    "location": [13.42044, 52.502907]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [23, 203, 293],
                    "duration": 4.407,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 5.59,
                    "geometry_index": 27,
                    "location": [13.420452, 52.502924]
                  },
                  {
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "location": [13.420579, 52.503106],
                    "geometry_index": 28,
                    "admin_index": 0,
                    "weight": 4.27,
                    "is_urban": true,
                    "traffic_signal": true,
                    "turn_duration": 2,
                    "turn_weight": 0.75,
                    "duration": 5.2,
                    "bearings": [23, 203],
                    "out": 0,
                    "in": 1,
                    "entry": [true, false]
                  },
                  {
                    "entry": [true, true, false, true],
                    "in": 2,
                    "bearings": [23, 114, 203, 294],
                    "duration": 1.267,
                    "turn_weight": 1.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.886,
                    "geometry_index": 30,
                    "location": [13.420672, 52.50324]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [23, 113, 203],
                    "duration": 1.447,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.334,
                    "geometry_index": 31,
                    "location": [13.420714, 52.503301]
                  },
                  {
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "location": [13.420762, 52.503369],
                    "geometry_index": 32,
                    "admin_index": 0,
                    "weight": 7.482,
                    "is_urban": true,
                    "traffic_signal": true,
                    "turn_duration": 2,
                    "turn_weight": 0.75,
                    "duration": 8.12,
                    "bearings": [24, 203],
                    "out": 0,
                    "in": 1,
                    "entry": [true, false]
                  },
                  {
                    "entry": [true, false, false, true],
                    "in": 2,
                    "bearings": [23, 113, 200, 294],
                    "duration": 7.208,
                    "turn_weight": 1.5,
                    "turn_duration": 0.008,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 9.42,
                    "geometry_index": 34,
                    "location": [13.420948, 52.503655]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [23, 203],
                    "duration": 1.44,
                    "turn_weight": 0.75,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.334,
                    "geometry_index": 35,
                    "location": [13.421184, 52.503988]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [23, 113, 203],
                    "duration": 1.987,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.928,
                    "geometry_index": 36,
                    "location": [13.421234, 52.504058]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [23, 203],
                    "duration": 1.44,
                    "turn_weight": 0.75,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.334,
                    "geometry_index": 37,
                    "location": [13.421299, 52.50415]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [23, 203, 294],
                    "duration": 5.227,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 6.492,
                    "geometry_index": 38,
                    "location": [13.421344, 52.504214]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [24, 203, 294],
                    "duration": 3.184,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 4.244,
                    "geometry_index": 39,
                    "location": [13.421517, 52.504457]
                  },
                  {
                    "entry": [true, false, false, true],
                    "in": 2,
                    "bearings": [24, 114, 204, 294],
                    "duration": 6.783,
                    "turn_weight": 1.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 8.954,
                    "geometry_index": 40,
                    "location": [13.421605, 52.504577]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [23, 113, 204],
                    "duration": 3.831,
                    "turn_weight": 0.75,
                    "turn_duration": 0.019,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 4.943,
                    "geometry_index": 41,
                    "location": [13.421799, 52.504843]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [23, 203],
                    "duration": 1.482,
                    "turn_weight": 0.75,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.381,
                    "geometry_index": 42,
                    "location": [13.421904, 52.504993]
                  },
                  {
                    "bearings": [24, 203],
                    "entry": [true, false],
                    "turn_weight": 0.75,
                    "in": 1,
                    "stop_sign": true,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "geometry_index": 43,
                    "location": [13.421947, 52.505054]
                  }
                ],
                "maneuver": {
                  "type": "turn",
                  "instruction": "Turn right onto Adalbertstraße.",
                  "modifier": "right",
                  "bearing_after": 23,
                  "bearing_before": 294,
                  "location": [13.419284, 52.501284]
                },
                "name": "Adalbertstraße",
                "duration": 96.237,
                "distance": 463.613,
                "driving_side": "right",
                "weight": 124.126,
                "mode": "driving",
                "geometry": "gqlccBgp`rXkDwBcAq@aFcDiIoFs@c@_]wTyByA_CwAwOuJy@g@]UsPgKa@WkJ}F}BuAmCcByBsAgC_BkJkGoEgBySwMkCcBwDaC_CyAeNyIoFoDsOcKkHqEyBuAUMwAaA"
              },
              {
                "intersections": [
                  {
                    "entry": [true, true, false, false],
                    "in": 2,
                    "bearings": [24, 99, 204, 280],
                    "duration": 2.015,
                    "turn_weight": 7,
                    "turn_duration": 0.935,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 1,
                    "weight": 8.188,
                    "geometry_index": 45,
                    "location": [13.421987, 52.505109]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [97, 203, 279],
                    "duration": 1.821,
                    "turn_weight": 0.75,
                    "turn_duration": 0.021,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.73,
                    "geometry_index": 46,
                    "location": [13.422115, 52.505097]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [96, 277],
                    "duration": 1.44,
                    "turn_weight": 0.75,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.334,
                    "geometry_index": 47,
                    "location": [13.422339, 52.50508]
                  },
                  {
                    "entry": [false, true, false],
                    "in": 2,
                    "bearings": [7, 91, 276],
                    "duration": 6.384,
                    "turn_weight": 0.75,
                    "turn_duration": 0.024,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 1,
                    "weight": 7.746,
                    "geometry_index": 48,
                    "location": [13.422509, 52.505069]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [86, 201, 269],
                    "duration": 9.382,
                    "turn_weight": 0.75,
                    "turn_duration": 0.022,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 11.046,
                    "geometry_index": 50,
                    "location": [13.423284, 52.505067]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [75, 199, 258],
                    "duration": 5.182,
                    "turn_weight": 0.75,
                    "turn_duration": 0.022,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 6.426,
                    "geometry_index": 53,
                    "location": [13.424426, 52.505167]
                  },
                  {
                    "entry": [true, true, false],
                    "in": 2,
                    "bearings": [67, 114, 250],
                    "duration": 0.262,
                    "turn_weight": 0.75,
                    "turn_duration": 0.022,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 1.014,
                    "geometry_index": 55,
                    "location": [13.425036, 52.505285]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [66, 247],
                    "duration": 11.16,
                    "turn_weight": 0.75,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 13.026,
                    "geometry_index": 56,
                    "location": [13.425067, 52.505293]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [52, 196, 237],
                    "duration": 2.426,
                    "turn_weight": 0.75,
                    "turn_duration": 0.026,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 3.39,
                    "geometry_index": 59,
                    "location": [13.426266, 52.50569]
                  },
                  {
                    "entry": [true, true, false, false],
                    "in": 2,
                    "bearings": [49, 115, 232, 346],
                    "duration": 1.489,
                    "turn_weight": 1.5,
                    "turn_duration": 0.022,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 3.113,
                    "geometry_index": 60,
                    "location": [13.426495, 52.5058]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 1,
                    "bearings": [47, 229, 284],
                    "duration": 11.889,
                    "turn_weight": 0.75,
                    "turn_duration": 0.022,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 13.803,
                    "geometry_index": 61,
                    "location": [13.426614, 52.505862]
                  },
                  {
                    "entry": [true, true, false],
                    "in": 2,
                    "bearings": [33, 173, 218],
                    "duration": 24.268,
                    "turn_weight": 0.75,
                    "turn_duration": 0.028,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 27.414,
                    "geometry_index": 64,
                    "location": [13.427512, 52.506445]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 1,
                    "bearings": [21, 205, 303],
                    "duration": 2.906,
                    "turn_weight": 0.75,
                    "turn_duration": 0.026,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 3.918,
                    "geometry_index": 70,
                    "location": [13.428196, 52.507253]
                  },
                  {
                    "entry": [true, true, false, true],
                    "in": 2,
                    "bearings": [6, 122, 201, 303],
                    "duration": 2.306,
                    "turn_weight": 3,
                    "turn_duration": 0.056,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 5.475,
                    "geometry_index": 71,
                    "location": [13.428259, 52.507353]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 1,
                    "bearings": [1, 186, 304],
                    "duration": 10.976,
                    "turn_weight": 0.5,
                    "turn_duration": 0.026,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 12.545,
                    "geometry_index": 72,
                    "location": [13.428283, 52.507484]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [24, 191, 206],
                    "duration": 1.817,
                    "turn_weight": 0.75,
                    "turn_duration": 0.017,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.73,
                    "geometry_index": 75,
                    "location": [13.42836, 52.508137]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 1,
                    "bearings": [24, 204, 293],
                    "duration": 7.078,
                    "turn_weight": 0.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 8.279,
                    "geometry_index": 76,
                    "location": [13.428443, 52.508249]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [29, 208, 315],
                    "duration": 3.464,
                    "turn_weight": 0.5,
                    "turn_duration": 0.008,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 4.302,
                    "geometry_index": 79,
                    "location": [13.428805, 52.508687]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 209],
                    "duration": 16.2,
                    "turn_weight": 5.5,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 23.32,
                    "geometry_index": 80,
                    "location": [13.428973, 52.508874]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [29, 208],
                    "duration": 3.6,
                    "turn_weight": 5.5,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 9.46,
                    "geometry_index": 81,
                    "location": [13.429608, 52.509587]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 209],
                    "duration": 7.457,
                    "turn_weight": 0.5,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 8.703,
                    "geometry_index": 82,
                    "location": [13.429708, 52.509697]
                  },
                  {
                    "bearings": [29, 122, 208],
                    "entry": [true, false, false],
                    "in": 2,
                    "turn_weight": 0.5,
                    "lanes": [
                      {
                        "indications": ["straight"],
                        "valid_indication": "straight",
                        "valid": true,
                        "active": true
                      },
                      {"indications": ["right"], "valid": false, "active": false}
                    ],
                    "turn_duration": 0.019,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "geometry_index": 83,
                    "location": [13.429909, 52.509924]
                  }
                ],
                "maneuver": {
                  "type": "turn",
                  "instruction": "Turn right onto Bethaniendamm.",
                  "modifier": "right",
                  "bearing_after": 99,
                  "bearing_before": 24,
                  "location": [13.421987, 52.505109]
                },
                "name": "Bethaniendamm",
                "duration": 136.212,
                "distance": 860.94,
                "driving_side": "right",
                "weight": 182.397,
                "mode": "driving",
                "geometry": "i`tccBeyerXV_G`@_MTsIJaZGkT[aVg@eNcCc`@wAaPsCaTO}@kDcSoGaZ}IwZ{EiM{BmF}G_O{NmXsJuMcKcLcLmJwHeEeEyCaFmDgAw@gE}BeGo@oIImQY{JuB_FeDyA_AmFmDcPeNuJoIqk@uf@{EgEeMqKcDqC"
              },
              {
                "intersections": [
                  {
                    "bearings": [209],
                    "entry": [true],
                    "in": 0,
                    "admin_index": 0,
                    "geometry_index": 84,
                    "location": [13.429982, 52.510006]
                  }
                ],
                "maneuver": {
                  "type": "arrive",
                  "instruction": "Your destination is on the right.",
                  "modifier": "right",
                  "bearing_after": 0,
                  "bearing_before": 29,
                  "location": [13.429982, 52.510006]
                },
                "name": "Bethaniendamm",
                "duration": 0,
                "distance": 0,
                "driving_side": "right",
                "weight": 0,
                "mode": "driving",
                "geometry": "kr}ccB{lurX??"
              }
            ],
            "distance": 1526.391,
            "summary": "Adalbertstraße, Bethaniendamm"
          }
        ],
        "geometry": "yjjccBcjbrXkk@ed@aY`~AanF}gDkEohDsp@ufCws@u_Ao^cU_p@iEysBkdB"
      },
      {
        "country_crossed": false,
        "weight_name": "auto",
        "weight": 527.309,
        "duration": 381.718,
        "distance": 1946.785,
        "legs": [
          {
            "via_waypoints": [],
            "admins": [{"iso_3166_1_alpha3": "DEU", "iso_3166_1": "DE"}],
            "weight": 527.309,
            "duration": 381.718,
            "steps": [
              {
                "intersections": [
                  {
                    "classes": ["restricted"],
                    "entry": [true],
                    "bearings": [27],
                    "duration": 2.52,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.772,
                    "geometry_index": 0,
                    "location": [13.42021, 52.500157]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["tunnel", "restricted"],
                    "in": 1,
                    "bearings": [28, 207],
                    "duration": 4.32,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 6.652,
                    "geometry_index": 1,
                    "location": [13.420257, 52.500214]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["restricted"],
                    "in": 1,
                    "bearings": [28, 208],
                    "duration": 5.76,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 8.236,
                    "geometry_index": 3,
                    "location": [13.42034, 52.50031]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["tunnel", "restricted"],
                    "in": 1,
                    "bearings": [27, 208],
                    "duration": 2.52,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 4.672,
                    "geometry_index": 4,
                    "location": [13.42045, 52.500436]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["restricted"],
                    "in": 1,
                    "bearings": [29, 207],
                    "duration": 8.64,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 11.404,
                    "geometry_index": 5,
                    "location": [13.420496, 52.500492]
                  },
                  {
                    "entry": [true, false],
                    "classes": ["tunnel", "restricted"],
                    "in": 1,
                    "bearings": [26, 209],
                    "duration": 4.68,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 7.048,
                    "geometry_index": 6,
                    "location": [13.420669, 52.500682]
                  },
                  {
                    "bearings": [21, 206],
                    "entry": [true, false],
                    "classes": ["restricted"],
                    "in": 1,
                    "turn_weight": 1.9,
                    "mapbox_streets_v8": {"class": "service"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "geometry_index": 7,
                    "location": [13.420753, 52.500786]
                  }
                ],
                "maneuver": {
                  "type": "depart",
                  "instruction": "Drive northeast.",
                  "bearing_after": 27,
                  "bearing_before": 0,
                  "location": [13.42021, 52.500157]
                },
                "name": "",
                "duration": 32.04,
                "distance": 88.795,
                "driving_side": "right",
                "weight": 46.644,
                "mode": "driving",
                "geometry": "yjjccBcjbrXqB}AyAmAeBwA{F{EoB{A{JyIoEgDaDgB"
              },
              {
                "intersections": [
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [114, 201, 294],
                    "duration": 26.823,
                    "turn_weight": 10.7,
                    "turn_duration": 2.423,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 37.54,
                    "geometry_index": 8,
                    "location": [13.420805, 52.500867]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [114, 295],
                    "duration": 3,
                    "turn_weight": 0.75,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 4.05,
                    "geometry_index": 10,
                    "location": [13.422439, 52.500414]
                  },
                  {
                    "entry": [false, true, true, false],
                    "in": 3,
                    "bearings": [37, 114, 177, 294],
                    "duration": 7.687,
                    "turn_weight": 6.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 1,
                    "weight": 14.948,
                    "geometry_index": 11,
                    "location": [13.422642, 52.500358]
                  },
                  {
                    "entry": [true, true, true, false],
                    "in": 3,
                    "bearings": [23, 115, 201, 294],
                    "duration": 5.947,
                    "turn_weight": 1.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 1,
                    "weight": 8.034,
                    "geometry_index": 14,
                    "location": [13.42307, 52.50024]
                  },
                  {
                    "entry": [true, false, false, true],
                    "in": 2,
                    "bearings": [114, 229, 294, 359],
                    "duration": 1.489,
                    "turn_weight": 6.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 8.131,
                    "geometry_index": 17,
                    "location": [13.423509, 52.500118]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [114, 294],
                    "duration": 20.329,
                    "turn_weight": 0.75,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 23.112,
                    "geometry_index": 18,
                    "location": [13.423608, 52.500091]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [114, 207, 294],
                    "duration": 5.089,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 6.341,
                    "geometry_index": 19,
                    "location": [13.4249, 52.499733]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [114, 204, 294],
                    "duration": 11.019,
                    "turn_weight": 0.75,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 12.863,
                    "geometry_index": 20,
                    "location": [13.425222, 52.499644]
                  },
                  {
                    "entry": [true, true, false],
                    "in": 2,
                    "bearings": [113, 204, 294],
                    "duration": 5.281,
                    "turn_weight": 0.75,
                    "turn_duration": 0.019,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 6.538,
                    "geometry_index": 21,
                    "location": [13.425927, 52.499449]
                  },
                  {
                    "bearings": [114, 293],
                    "entry": [true, false],
                    "in": 1,
                    "turn_weight": 0.75,
                    "mapbox_streets_v8": {"class": "tertiary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "geometry_index": 23,
                    "location": [13.426186, 52.499381]
                  }
                ],
                "maneuver": {
                  "type": "end of road",
                  "instruction": "Turn right onto Oranienstraße.",
                  "modifier": "right",
                  "bearing_after": 114,
                  "bearing_before": 21,
                  "location": [13.420805, 52.500867]
                },
                "name": "Oranienstraße",
                "duration": 91.096,
                "distance": 416.886,
                "driving_side": "right",
                "weight": 127.18,
                "mode": "driving",
                "geometry": "ewkccBiocrXtXu{ArAmHnBuKfCoN\\kBdA{FbAuFXyAtC}Ot@eEjUwoApDcSdKak@hBuK\\oBvB{L"
              },
              {
                "intersections": [
                  {
                    "entry": [true, true, true, false],
                    "in": 3,
                    "bearings": [28, 124, 208, 294],
                    "duration": 7.224,
                    "turn_weight": 12.5,
                    "turn_duration": 4.894,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 15.062,
                    "geometry_index": 24,
                    "location": [13.426408, 52.499321]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 208],
                    "duration": 19.694,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 22.664,
                    "geometry_index": 25,
                    "location": [13.426488, 52.499411]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 208],
                    "duration": 2.541,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 3.795,
                    "geometry_index": 27,
                    "location": [13.427122, 52.500151]
                  },
                  {
                    "entry": [true, false, true, false],
                    "in": 1,
                    "bearings": [29, 208, 296, 344],
                    "duration": 3.968,
                    "turn_weight": 1,
                    "turn_duration": 0.008,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 5.356,
                    "geometry_index": 28,
                    "location": [13.427205, 52.500248]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 208],
                    "duration": 16.56,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 19.216,
                    "geometry_index": 30,
                    "location": [13.427356, 52.500418]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [27, 208],
                    "duration": 1.44,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.584,
                    "geometry_index": 31,
                    "location": [13.427991, 52.501152]
                  },
                  {
                    "entry": [true, true, false, true],
                    "in": 2,
                    "bearings": [27, 113, 207, 291],
                    "duration": 1.152,
                    "turn_weight": 2,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 3.26,
                    "geometry_index": 32,
                    "location": [13.428043, 52.501213]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 207],
                    "duration": 10.309,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 12.34,
                    "geometry_index": 33,
                    "location": [13.428089, 52.501269]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [27, 117, 208],
                    "duration": 3.128,
                    "turn_weight": 1,
                    "turn_duration": 0.019,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 4.42,
                    "geometry_index": 34,
                    "location": [13.428525, 52.501769]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 2,
                    "bearings": [28, 118, 207],
                    "duration": 4.753,
                    "turn_weight": 1,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 6.22,
                    "geometry_index": 35,
                    "location": [13.428652, 52.501919]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 1,
                    "bearings": [28, 208, 300],
                    "duration": 3.28,
                    "turn_weight": 1,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 4.6,
                    "geometry_index": 36,
                    "location": [13.428853, 52.502152]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [27, 208],
                    "duration": 1.473,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.62,
                    "geometry_index": 37,
                    "location": [13.428991, 52.502312]
                  },
                  {
                    "entry": [true, true, false, true],
                    "in": 2,
                    "bearings": [28, 122, 207, 298],
                    "duration": 1.26,
                    "turn_weight": 2,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 3.377,
                    "geometry_index": 38,
                    "location": [13.429054, 52.502386]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 208],
                    "duration": 2.348,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 3.583,
                    "geometry_index": 39,
                    "location": [13.42911, 52.502451]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 1,
                    "bearings": [28, 208, 297],
                    "duration": 16.911,
                    "turn_weight": 1,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 19.595,
                    "geometry_index": 40,
                    "location": [13.429213, 52.502568]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [29, 207],
                    "duration": 1.409,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.55,
                    "geometry_index": 42,
                    "location": [13.429957, 52.503425]
                  },
                  {
                    "entry": [true, true, false, true],
                    "in": 2,
                    "bearings": [28, 125, 209, 303],
                    "duration": 1.333,
                    "turn_weight": 2,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 3.459,
                    "geometry_index": 43,
                    "location": [13.430024, 52.503499]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 208],
                    "duration": 38.274,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 43.101,
                    "geometry_index": 44,
                    "location": [13.430076, 52.503558]
                  },
                  {
                    "entry": [true, true, false],
                    "in": 2,
                    "bearings": [28, 118, 208],
                    "duration": 10.996,
                    "turn_weight": 1,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 13.088,
                    "geometry_index": 46,
                    "location": [13.431461, 52.505163]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [27, 209],
                    "duration": 0.758,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 1.834,
                    "geometry_index": 49,
                    "location": [13.43186, 52.50562]
                  },
                  {
                    "bearings": [28, 207],
                    "entry": [true, false],
                    "in": 1,
                    "turn_weight": 1,
                    "mapbox_streets_v8": {"class": "street"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "geometry_index": 50,
                    "location": [13.431889, 52.505654]
                  }
                ],
                "maneuver": {
                  "type": "turn",
                  "instruction": "Turn left onto Manteuffelstraße.",
                  "modifier": "left",
                  "bearing_after": 28,
                  "bearing_before": 114,
                  "location": [13.426408, 52.499321]
                },
                "name": "Manteuffelstraße",
                "duration": 151.274,
                "distance": 809.48,
                "driving_side": "right",
                "weight": 196.433,
                "mode": "driving",
                "geometry": "qvhccBomnrXsD_D{BkBki@gc@aEeDmD}CeDoC{l@uf@yBgBoB{Ag^gZkH}FqMqK_IsGsC}BaCoBiFmEeo@_i@kDoCsCeCuBgBmCyB{~AwqAuTuQ_@g@{D_DcAy@gEmD"
              },
              {
                "intersections": [
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [125, 208, 305],
                    "duration": 6.145,
                    "turn_weight": 18.75,
                    "turn_duration": 4.345,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 20.73,
                    "geometry_index": 51,
                    "location": [13.431976, 52.505754]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [37, 125, 304],
                    "duration": 3.758,
                    "turn_weight": 0.5,
                    "turn_duration": 0.019,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 4.612,
                    "geometry_index": 53,
                    "location": [13.431828, 52.505818]
                  },
                  {
                    "entry": [false, true, true],
                    "in": 0,
                    "bearings": [124, 214, 306],
                    "duration": 2.768,
                    "turn_weight": 0.5,
                    "turn_duration": 0.008,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 3.536,
                    "geometry_index": 54,
                    "location": [13.431493, 52.505957]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [37, 126, 306],
                    "duration": 2.562,
                    "turn_weight": 0.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 3.31,
                    "geometry_index": 55,
                    "location": [13.431214, 52.506082]
                  },
                  {
                    "entry": [false, true, true],
                    "in": 0,
                    "bearings": [126, 210, 305],
                    "duration": 8.136,
                    "turn_weight": 0.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 9.442,
                    "geometry_index": 56,
                    "location": [13.430954, 52.506196]
                  },
                  {
                    "entry": [false, true, true],
                    "in": 0,
                    "bearings": [125, 206, 305],
                    "duration": 4.122,
                    "turn_weight": 0.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 5.026,
                    "geometry_index": 57,
                    "location": [13.430104, 52.50656]
                  },
                  {
                    "entry": [false, true, true],
                    "in": 0,
                    "bearings": [125, 213, 305],
                    "duration": 5.047,
                    "turn_weight": 0.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 6.044,
                    "geometry_index": 58,
                    "location": [13.429716, 52.506726]
                  },
                  {
                    "entry": [false, true],
                    "in": 0,
                    "bearings": [125, 305],
                    "duration": 2.016,
                    "turn_weight": 0.5,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 1,
                    "weight": 2.718,
                    "geometry_index": 59,
                    "location": [13.429292, 52.506905]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [37, 125, 309],
                    "duration": 3.608,
                    "turn_weight": 0.5,
                    "turn_duration": 0.008,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "weight": 4.46,
                    "geometry_index": 60,
                    "location": [13.429123, 52.506976]
                  },
                  {
                    "bearings": [129, 204, 306],
                    "entry": [false, true, true],
                    "in": 0,
                    "turn_weight": 0.5,
                    "turn_duration": 0.024,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 2,
                    "geometry_index": 61,
                    "location": [13.428881, 52.507095]
                  }
                ],
                "maneuver": {
                  "type": "end of road",
                  "instruction": "Turn left onto Köpenicker Straße.",
                  "modifier": "left",
                  "bearing_after": 305,
                  "bearing_before": 28,
                  "location": [13.431976, 52.505754]
                },
                "name": "Köpenicker Straße",
                "duration": 51.301,
                "distance": 308.487,
                "driving_side": "right",
                "weight": 74.804,
                "mode": "driving",
                "geometry": "shuccBoiyrXmBzFQj@uG|SyFlPcFfOwUbt@kIfWeJnYmCpImFbNuAdEsDzKiB`Gq@`C}AtF"
              },
              {
                "intersections": [
                  {
                    "entry": [true, false, false, true],
                    "in": 1,
                    "bearings": [6, 123, 201, 303],
                    "duration": 2.728,
                    "turn_weight": 7,
                    "turn_duration": 0.478,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 9.475,
                    "geometry_index": 66,
                    "location": [13.428259, 52.507353]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 1,
                    "bearings": [1, 186, 304],
                    "duration": 10.976,
                    "turn_weight": 0.5,
                    "turn_duration": 0.026,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 12.545,
                    "geometry_index": 67,
                    "location": [13.428283, 52.507484]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [24, 191, 206],
                    "duration": 1.817,
                    "turn_weight": 0.75,
                    "turn_duration": 0.017,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 2.73,
                    "geometry_index": 70,
                    "location": [13.42836, 52.508137]
                  },
                  {
                    "entry": [true, false, false],
                    "in": 1,
                    "bearings": [24, 204, 293],
                    "duration": 7.078,
                    "turn_weight": 0.5,
                    "turn_duration": 0.007,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 8.279,
                    "geometry_index": 71,
                    "location": [13.428443, 52.508249]
                  },
                  {
                    "entry": [true, false, true],
                    "in": 1,
                    "bearings": [29, 208, 315],
                    "duration": 3.464,
                    "turn_weight": 0.5,
                    "turn_duration": 0.008,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 4.302,
                    "geometry_index": 74,
                    "location": [13.428805, 52.508687]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 209],
                    "duration": 16.2,
                    "turn_weight": 5.5,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 23.32,
                    "geometry_index": 75,
                    "location": [13.428973, 52.508874]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [29, 208],
                    "duration": 3.6,
                    "turn_weight": 5.5,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 9.46,
                    "geometry_index": 76,
                    "location": [13.429608, 52.509587]
                  },
                  {
                    "entry": [true, false],
                    "in": 1,
                    "bearings": [28, 209],
                    "duration": 7.457,
                    "turn_weight": 0.5,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "weight": 8.703,
                    "geometry_index": 77,
                    "location": [13.429708, 52.509697]
                  },
                  {
                    "bearings": [29, 122, 208],
                    "entry": [true, false, false],
                    "in": 2,
                    "turn_weight": 0.5,
                    "lanes": [
                      {
                        "indications": ["straight"],
                        "valid_indication": "straight",
                        "valid": true,
                        "active": true
                      },
                      {"indications": ["right"], "valid": false, "active": false}
                    ],
                    "turn_duration": 0.019,
                    "mapbox_streets_v8": {"class": "secondary"},
                    "is_urban": true,
                    "admin_index": 0,
                    "out": 0,
                    "geometry_index": 78,
                    "location": [13.429909, 52.509924]
                  }
                ],
                "maneuver": {
                  "type": "turn",
                  "instruction": "Turn right onto Bethaniendamm.",
                  "modifier": "right",
                  "bearing_after": 6,
                  "bearing_before": 303,
                  "location": [13.428259, 52.507353]
                },
                "name": "Bethaniendamm",
                "duration": 56.008,
                "distance": 323.137,
                "driving_side": "right",
                "weight": 82.249,
                "mode": "driving",
                "geometry": "qlxccBearrXeGo@oIImQY{JuB_FeDyA_AmFmDcPeNuJoIqk@uf@{EgEeMqKcDqC"
              },
              {
                "intersections": [
                  {
                    "bearings": [209],
                    "entry": [true],
                    "in": 0,
                    "admin_index": 0,
                    "geometry_index": 79,
                    "location": [13.429982, 52.510006]
                  }
                ],
                "maneuver": {
                  "type": "arrive",
                  "instruction": "Your destination is on the right.",
                  "modifier": "right",
                  "bearing_after": 0,
                  "bearing_before": 29,
                  "location": [13.429982, 52.510006]
                },
                "name": "Bethaniendamm",
                "duration": 0,
                "distance": 0,
                "driving_side": "right",
                "weight": 0,
                "mode": "driving",
                "geometry": "kr}ccB{lurX??"
              }
            ],
            "distance": 1946.785,
            "summary": "Oranienstraße, Manteuffelstraße"
          }
        ],
        "geometry": "yjjccBcjbrXkk@ed@r_Be}IaqK_{I}bBhgF_p@iEysBkdB"
      }
    ],
    "waypoints": [
      {"distance": 22.538, "name": "", "location": [13.42021, 52.500157]},
      {
        "distance": 1.369,
        "name": "An der Schillingbrücke",
        "location": [13.429982, 52.510006]
      }
    ],
    "code": "Ok",
    "uuid": "00DU5MqrU7CpvaPiXVT00E3-M9ZsOQ-C1nTAul41-M_ognIdviFD_w=="
  }

export default response;  